### ISSUE TITLE
Release 1.2.0 then remove support for old Python/Django?

### ISSUE THREAD

**Issue by frankier** [fusionbox/django-betterforms#32] opened 2015-08-19 16:44 UTC
I think it might be an idea to release 1.2.0 based on the current HEAD, and then remove support for Python 2.6 and Django <1.7 , to make it easier to support Django 1.8 and to allow improvements to the form api such as https://github.com/fusionbox/django-betterforms/issues/14 to be adopted.

**Comment by Zopieux** [comment] 2015-10-14 21:58
I second that idea. :+1:

**Comment by acatton** [comment] 2015-10-15 19:28
This is a duplicate of #37 which has a TODO list.

**Closed by acatton** 2015-10-15 19:28 UTC
